# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quantification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='quantification.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14quantification.proto\"\xaf\x03\n\x0eQuantification\x12\x0e\n\x06labels\x18\x01 \x03(\t\x12,\n\x05types\x18\x02 \x03(\x0e\x32\x1d.Quantification.QuantDataType\x12\x35\n\x0blocationSet\x18\x03 \x03(\x0b\x32 .Quantification.QuantLocationSet\x1a\xa5\x01\n\rQuantLocation\x12\x0b\n\x03pmc\x18\x01 \x01(\x05\x12\x0b\n\x03rtt\x18\x02 \x01(\x05\x12\x0c\n\x04sclk\x18\x03 \x01(\x05\x12;\n\x06values\x18\x05 \x03(\x0b\x32+.Quantification.QuantLocation.QuantDataItem\x1a/\n\rQuantDataItem\x12\x0e\n\x06\x66value\x18\x02 \x01(\x02\x12\x0e\n\x06ivalue\x18\x03 \x01(\x05\x1aU\n\x10QuantLocationSet\x12\x10\n\x08\x64\x65tector\x18\x01 \x01(\t\x12/\n\x08location\x18\x02 \x03(\x0b\x32\x1d.Quantification.QuantLocation\")\n\rQuantDataType\x12\x0c\n\x08QT_FLOAT\x10\x00\x12\n\n\x06QT_INT\x10\x01\x42\nZ\x08.;protosb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_QUANTIFICATION_QUANTDATATYPE = _descriptor.EnumDescriptor(
  name='QuantDataType',
  full_name='Quantification.QuantDataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QT_FLOAT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QT_INT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=415,
  serialized_end=456,
)
_sym_db.RegisterEnumDescriptor(_QUANTIFICATION_QUANTDATATYPE)


_QUANTIFICATION_QUANTLOCATION_QUANTDATAITEM = _descriptor.Descriptor(
  name='QuantDataItem',
  full_name='Quantification.QuantLocation.QuantDataItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fvalue', full_name='Quantification.QuantLocation.QuantDataItem.fvalue', index=0,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ivalue', full_name='Quantification.QuantLocation.QuantDataItem.ivalue', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=326,
)

_QUANTIFICATION_QUANTLOCATION = _descriptor.Descriptor(
  name='QuantLocation',
  full_name='Quantification.QuantLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pmc', full_name='Quantification.QuantLocation.pmc', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtt', full_name='Quantification.QuantLocation.rtt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sclk', full_name='Quantification.QuantLocation.sclk', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='Quantification.QuantLocation.values', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_QUANTIFICATION_QUANTLOCATION_QUANTDATAITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=326,
)

_QUANTIFICATION_QUANTLOCATIONSET = _descriptor.Descriptor(
  name='QuantLocationSet',
  full_name='Quantification.QuantLocationSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detector', full_name='Quantification.QuantLocationSet.detector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='Quantification.QuantLocationSet.location', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=413,
)

_QUANTIFICATION = _descriptor.Descriptor(
  name='Quantification',
  full_name='Quantification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='Quantification.labels', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='types', full_name='Quantification.types', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='locationSet', full_name='Quantification.locationSet', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_QUANTIFICATION_QUANTLOCATION, _QUANTIFICATION_QUANTLOCATIONSET, ],
  enum_types=[
    _QUANTIFICATION_QUANTDATATYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=456,
)

_QUANTIFICATION_QUANTLOCATION_QUANTDATAITEM.containing_type = _QUANTIFICATION_QUANTLOCATION
_QUANTIFICATION_QUANTLOCATION.fields_by_name['values'].message_type = _QUANTIFICATION_QUANTLOCATION_QUANTDATAITEM
_QUANTIFICATION_QUANTLOCATION.containing_type = _QUANTIFICATION
_QUANTIFICATION_QUANTLOCATIONSET.fields_by_name['location'].message_type = _QUANTIFICATION_QUANTLOCATION
_QUANTIFICATION_QUANTLOCATIONSET.containing_type = _QUANTIFICATION
_QUANTIFICATION.fields_by_name['types'].enum_type = _QUANTIFICATION_QUANTDATATYPE
_QUANTIFICATION.fields_by_name['locationSet'].message_type = _QUANTIFICATION_QUANTLOCATIONSET
_QUANTIFICATION_QUANTDATATYPE.containing_type = _QUANTIFICATION
DESCRIPTOR.message_types_by_name['Quantification'] = _QUANTIFICATION

Quantification = _reflection.GeneratedProtocolMessageType('Quantification', (_message.Message,), dict(

  QuantLocation = _reflection.GeneratedProtocolMessageType('QuantLocation', (_message.Message,), dict(

    QuantDataItem = _reflection.GeneratedProtocolMessageType('QuantDataItem', (_message.Message,), dict(
      DESCRIPTOR = _QUANTIFICATION_QUANTLOCATION_QUANTDATAITEM,
      __module__ = 'quantification_pb2'
      # @@protoc_insertion_point(class_scope:Quantification.QuantLocation.QuantDataItem)
      ))
    ,
    DESCRIPTOR = _QUANTIFICATION_QUANTLOCATION,
    __module__ = 'quantification_pb2'
    # @@protoc_insertion_point(class_scope:Quantification.QuantLocation)
    ))
  ,

  QuantLocationSet = _reflection.GeneratedProtocolMessageType('QuantLocationSet', (_message.Message,), dict(
    DESCRIPTOR = _QUANTIFICATION_QUANTLOCATIONSET,
    __module__ = 'quantification_pb2'
    # @@protoc_insertion_point(class_scope:Quantification.QuantLocationSet)
    ))
  ,
  DESCRIPTOR = _QUANTIFICATION,
  __module__ = 'quantification_pb2'
  # @@protoc_insertion_point(class_scope:Quantification)
  ))
_sym_db.RegisterMessage(Quantification)
_sym_db.RegisterMessage(Quantification.QuantLocation)
_sym_db.RegisterMessage(Quantification.QuantLocation.QuantDataItem)
_sym_db.RegisterMessage(Quantification.QuantLocationSet)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\010.;protos'))
# @@protoc_insertion_point(module_scope)
